[auth]
enabled = true
site_url = "https://mcafee-refund-portal.vercel.app"
additional_redirect_urls = [
  "https://mcafee-refund-portal.vercel.app",
  "https://mcafee-refund-portal.vercel.app/?password-reset=1",
  "https://mcafee-refund-portal.vercel.app/**",
  "https://mcafee-refund-portal-codingbrain02s-projects.vercel.app/**",
  "https://mcafee-refund-portal-git-main-codingbrain02s-projects.vercel.app/**",
]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change = false
max_frequency = "1m0s"
otp_length = 8
otp_expiry = 3600

[auth.mfa]
max_enrolled_factors = 10

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.mfa.phone]
enroll_enabled = false
verify_enabled = false
otp_length = 6
template = "Your code is {{ .Code }}"
max_frequency = "5s"

[storage.vector]
enabled = false
max_buckets = 10
max_indexes = 5
